Repository ocean-ds/ocean-tokens, pull requests merged in 2020-07, with the labels that each got.

#50 feat: includes font types
  assets/fonts/Avenir/Avenir-Black.ttf
  assets/fonts/Avenir/Avenir-Black.woff2
  assets/fonts/Avenir/Avenir-Heavy.ttf
  assets/fonts/Avenir/Avenir-Heavy.woff2
  assets/fonts/Avenir/Avenir-Light.ttf
  assets/fonts/Avenir/Avenir-Light.woff2
  assets/fonts/Avenir/Avenir-Medium.ttf
  assets/fonts/Avenir/Avenir-Medium.woff2
  assets/fonts/Avenir/Avenir-Roman.ttf
  assets/fonts/Avenir/Avenir-Roman.woff2
  assets/fonts/NunitoSans/NunitoSans-Bold.ttf
  assets/fonts/NunitoSans/NunitoSans-Bold.woff2
  assets/fonts/NunitoSans/NunitoSans-ExtraBold.ttf
  assets/fonts/NunitoSans/NunitoSans-ExtraBold.woff2
  assets/fonts/NunitoSans/NunitoSans-Light.ttf
  assets/fonts/NunitoSans/NunitoSans-Light.woff2
  assets/fonts/NunitoSans/NunitoSans-Regular.ttf
  assets/fonts/NunitoSans/NunitoSans-Regular.woff2
  assets/fonts/NunitoSans/NunitoSans-SemiBold.ttf
  assets/fonts/NunitoSans/NunitoSans-SemiBold.woff2
Labels: enhancement, help wanted

#51 feat: mobile build configs
  .circleci/config.yml
  .eslintignore
  .eslintrc.js
  .gitignore
  .prettierignore
  .prettierrc
  .vscode/launch.json
  build/android/formatToXML.js
  build/android/index.js
  build/android/setupTheo.js
  build/doc/index.js
  build/ios/formatToJSON.js
  build/ios/index.js
  build/ios/setupTheo.js
  build/utils/gulpLoadFiles.js
  build/utils/mobileGlobs.js
  build/utils/theoReplaceAll.js
  build/utils/withName.js
  build/web/index.js
  formats/android/pre-script.js
  formats/formats.js
  gulpfile.js
  package.json
  scripts/gulpfile.js
  yarn.lock
Labels: enhancement, help wanted

#52 ci: create trigger for generate pod file automatically
  .circleci/config.yml
Labels: dependencies, enhancement

#53 feat: Include fonts declaration file
  assets/css/fonts.css
Labels: enhancement

#55 docs: updates change log for 2.0.0 version
  CHANGELOG.md
Labels: documentation
