Repository ocean-ds/ocean-tokens, pull requests merged in 2020-06, with the labels that each got.

#39 Create CONTRIBUTING.md
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  package.json
Labels: documentation, help wanted

#38 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation, help wanted

#40 Circleci project setup
  .circleci/config.yml
  README.md
  formats/android/android-formats.js
  formats/android/blu.android.xml.js
  formats/android/pre-script.js
  formats/formats.js
  package.json
  scripts/gulpfile.js
  yarn.lock
Labels: enhancement

#41 ci: Adds prlint
  .github/prlint.json
Labels: enhancement

#43 ci: Circle ci deploy npm
  .circleci/config.yml
  package.json
  yarn.lock
Labels: enhancement, help wanted

#44 ci: configuring job filters
  .circleci/config.yml
Labels: enhancement

#46 docs: Update documentations
  .vscode/extensions.json
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/High-LevelTokenHierarchy
Labels: documentation, help wanted

#47 feat: Update change log
  CHANGELOG.md
Labels: enhancement, help wanted
